config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :dinosaurs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/Cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  def index
    @cars = Car.all
		@car = Car.new 
	end

  # GET /cars/1
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  def create
		@cars = Car.all
    @car = Car.new(car_params)

		respond_to do |format|
			if @car.save
				format.js
			else
			  format.html {	render :index }
			end
		end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      redirect_to @car, notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
    redirect_to cars_url, notice: 'Car was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  before_action :set_dinosaur, only: [:show, :edit, :update, :destroy]

  # GET /dinosaurs
  def index
    @dinosaurs = Dinosaur.all
		@dinosaur = Dinosaur.new
  end

  # GET /dinosaurs/1
  def show
  end

  # GET /dinosaurs/new
  def new
    @dinosaur = Dinosaur.new
  end

  # GET /dinosaurs/1/edit
  def edit
  end

  # POST /dinosaurs
  def create
		@dinosaurs = Dinosaur.all
    @dinosaur = Dinosaur.new(dinosaur_params)

    if @dinosaur.save
      redirect_to dinosaurs_path, notice: 'Dinosaur was successfully created.' 
		else 
			render :index
    end
  end

  # PATCH/PUT /dinosaurs/1
  def update
    if @dinosaur.update(dinosaur_params)
      redirect_to @dinosaur, notice: 'Dinosaur was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /dinosaurs/1
  def destroy
    @dinosaur.destroy
    redirect_to dinosaurs_url, notice: 'Dinosaur was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dinosaur
      @dinosaur = Dinosaur.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def dinosaur_params
      params.require(:dinosaur).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/cars/_car.html.erb
<tr>
	<td><%= car.name %></td>
	<td><%= link_to 'Show', car %></td>
	<td><%= link_to 'Edit', edit_car_path(car) %></td>
	<td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/create.js.erb
// render car
var body = document.getElementById("cars");
body.innerHTML = "<%= j render @car %>" + body.innerHTML;

// clear and focus on input
var input = document.getElementById("car_name");
input.value = '';
input.focus();

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<%= render 'form', car: @car %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='cars'>
		<%= render @cars %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/dinosaurs/_form.html.erb
<%= form_with(model: dinosaur, local: true) do |form| %>
  <% if dinosaur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dinosaur.errors.count, "error") %> prohibited this dinosaur from being saved:</h2>

      <ul>
        <% dinosaur.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dinosaurs/edit.html.erb
<h1>Editing Dinosaur</h1>

<%= render 'form', dinosaur: @dinosaur %>

<%= link_to 'Show', @dinosaur %> |
<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dinosaurs</h1>

<%= render 'form', dinosaur: @dinosaur %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dinosaurs.each do |dinosaur| %>
      <tr>
        <td><%= dinosaur.name %></td>
        <td><%= link_to 'Show', dinosaur %></td>
        <td><%= link_to 'Edit', edit_dinosaur_path(dinosaur) %></td>
        <td><%= link_to 'Destroy', dinosaur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dinosaur', new_dinosaur_path %>

app/views/dinosaurs/new.html.erb
<h1>New Dinosaur</h1>

<%= render 'form', dinosaur: @dinosaur %>

<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dinosaur.name %>
</p>

<%= link_to 'Edit', edit_dinosaur_path(@dinosaur) %> |
<%= link_to 'Back', dinosaurs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SjrBasics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>